disagg_moonshotai/Kimi-K2.5_h200_sxm_h200_sxm_vllm_0.12.0_4000_500_0_2000.0_50.0:
  attention_backend: flashinfer
  backend_name: vllm
  backend_version: 0.12.0
  config:
    advanced_tuning_config:
      decode_latency_correction_scale: 1.08
      decode_max_batch_size: 512
      prefill_latency_correction_scale: 1.1
      prefill_max_batch_size: 1
    decode_worker_config:
      attention_backend: flashinfer
      backend_name: vllm
      backend_version: 0.12.0
      comm_quant_mode: half
      dp_list: [1, 2, 4, 8, 16, 32, 64, 128]
      enable_eplb: null
      enable_wideep: false
      fmha_quant_mode: float16
      gemm_quant_mode: float16
      kvcache_quant_mode: float16
      moe_backend: null
      moe_ep_list: [1, 2, 4, 8, 16, 32, 64, 128]
      moe_quant_mode: float16
      moe_tp_list: [1, 2, 4, 8, 16, 32, 64, 128]
      num_gpu_per_worker: [1, 2, 4, 8, 16, 32]
      pp_list: [1]
      system_name: h200_sxm
      tp_list: [1, 2, 4, 8, 16, 32, 64, 128]
    nextn: 0
    nextn_accept_rates: [0.85, 0.3, 0.0, 0.0, 0.0]
    prefill_worker_config:
      attention_backend: flashinfer
      backend_name: vllm
      backend_version: 0.12.0
      comm_quant_mode: half
      dp_list: [1, 2, 4, 8, 16, 32, 64, 128]
      enable_eplb: null
      enable_wideep: false
      fmha_quant_mode: float16
      gemm_quant_mode: float16
      kvcache_quant_mode: float16
      moe_backend: null
      moe_ep_list: [1, 2, 4, 8, 16, 32, 64, 128]
      moe_quant_mode: float16
      moe_tp_list: [1, 2, 4, 8, 16, 32, 64, 128]
      num_gpu_per_worker: [1, 2, 4, 8, 16, 32]
      pp_list: [1]
      system_name: h200_sxm
      tp_list: [1, 2, 4, 8, 16, 32, 64, 128]
    replica_config:
      max_decode_worker: 32
      max_gpu_per_replica: 32
      max_prefill_worker: 32
      num_gpu_per_replica: [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96,
        104, 112, 120, 128]
  decode_system_name: h200_sxm
  enable_wideep: false
  isl: 4000
  mode: patch
  model_path: moonshotai/Kimi-K2.5
  moe_backend: null
  osl: 500
  prefix: 0
  profiles: []
  serving_mode: disagg
  system_name: h200_sxm
  total_gpus: 32
  tpot: 50.0
  ttft: 2000.0
