agg_moonshotai/Kimi-K2.5_h200_sxm_vllm_0.12.0_4000_500_0_2000.0_50.0:
  attention_backend: flashinfer
  backend_name: vllm
  backend_version: 0.12.0
  config:
    nextn: 0
    nextn_accept_rates: [0.85, 0.3, 0.0, 0.0, 0.0]
    worker_config:
      backend_name: vllm
      backend_version: 0.12.0
      comm_quant_mode: half
      dp_list: [1, 2, 4, 8, 16, 32, 64, 128]
      fmha_quant_mode: float16
      gemm_quant_mode: float16
      kvcache_quant_mode: float16
      moe_ep_list: [1, 2, 4, 8, 16, 32, 64, 128]
      moe_quant_mode: float16
      moe_tp_list: [1, 2, 4, 8, 16, 32, 64, 128]
      num_gpu_per_worker: [1, 2, 4, 8, 16, 32]
      pp_list: [1]
      system_name: h200_sxm
      tp_list: [1, 2, 4, 8, 16, 32, 64, 128]
  enable_wideep: false
  isl: 4000
  mode: patch
  model_path: moonshotai/Kimi-K2.5
  moe_backend: null
  osl: 500
  prefix: 0
  profiles: []
  serving_mode: agg
  system_name: h200_sxm
  total_gpus: 32
  tpot: 50.0
  ttft: 2000.0
